version: '3.8'

networks:
  dia_dev_net:
    driver: bridge

volumes:
  data:
  dia_dev_storage_redis:


services:
  storage_minio:
    image: minio/minio:latest
    command: minio server /data --console-address ":9001" --address ":9000"
    container_name: test.storage.minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_REGION_NAME: us-east-1
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - data:/data:rw
    networks:
      - dia_dev_net

  redis:
    image: redis:latest
    container_name: test.storage.redis
    ports:
      - 6379:6379
    networks:
      - dia_dev_net
    volumes:
      - dia_dev_storage_redis:/data:rw

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 start_worker.py
    depends_on:
      - redis
      - storage_minio
    environment:
      - CELERY_BROKER_URL=redis://test.storage.redis:6379/0
      - CELERY_RESULT_BACKEND=redis://test.storage.redis:6379/0
    networks:
      - dia_dev_net

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --reload
    depends_on:
      - storage_minio
      - redis
      - worker
    ports:
      - 8000:8000
    environment:
      - STREAM_DELAY=1 second
      - MINIO_URL=test.storage.minio:9000
      - MINIO_ACCESS_KEY=zubgj6gLGPzFhOpONBBf
      - MINIO_SECRET_KEY=D867vMKEwZ6uLZusWmSZcg6etTXwGaNX7Nym0Txu
      - MINIO_BUCKET_NAME=test-bucket
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAX_CHUNK_SIZE=15 MB
      - MAX_DOWNLOAD_SIZE=15 MB
      - REDIS_EXPIRE_TIME=1 day
      - MINIO_EXPIRE_TIME=1 day
      - S3_URL=http://test.storage.minio:9000
      - S3_ACCESS_KEY=zubgj6gLGPzFhOpONBBf
      - S3_SECRET_KEY=D867vMKEwZ6uLZusWmSZcg6etTXwGaNX7Nym0Txu
      - S3_BUCKET_NAME=test-bucket
    networks:
      - dia_dev_net
    volumes:
      - ./:/backend_download:rw

  minio_client:
    image: minio/mc:latest
    depends_on:
      - storage_minio
    entrypoint: >
      /bin/sh -c "
        /usr/bin/mc alias set myminio http://test.storage.minio:9000 minioadmin minioadmin || exit 1; 
        #/usr/bin/mc rb --force myminio/documents;
        #/usr/bin/mc rb --force myminio/videos;
        /usr/bin/mc rb --force myminio/test-bucket;
        /usr/bin/mc mb myminio/test-bucket || exit 1; 
        /usr/bin/mc cp --recursive /_data/ myminio/test-bucket/;
        /usr/bin/mc policy set public myminio/test-bucket;
        exit 0;
      "
    networks:
      - dia_dev_net
    volumes:
      - ./_data:/_data:rw

  # flower:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - worker
  #     - redis
  #   command: celery -A worker flower --port=5555
  #   ports:
  #     - 5555:5555
  #   networks:
  #     - dia_dev_net